name: Deploy XTalk Function

on:
  push:
    branches: [main]  # O cambia a la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: dm-data-aiml
        install_components: 'beta'

    - name: Configure Docker to use gcloud as a credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Docker build (amd64)
      run: |
        docker buildx build --platform linux/amd64 -t xtalk_function_v1:1.0.0 . --load

    - name: Docker tag and push to Artifact Registry A
      run: |
        docker tag xtalk_function_v1:1.0.0 us-central1-docker.pkg.dev/dm-data-aiml/xtalk-function-v1/xtalk_function_v1:1.0.0
        docker push us-central1-docker.pkg.dev/dm-data-aiml/xtalk-function-v1/xtalk_function_v1:1.0.0

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy xtalk-function-v1 \
          --image=us-central1-docker.pkg.dev/dm-data-aiml/xtalk-function-v1/xtalk_function_v1:1.0.0 \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --project=dm-data-aiml \
          --memory=4Gi \
          --cpu=4 \
          --concurrency=16 \
          --service-account=dm-data-aiml@dm-data-aiml.iam.gserviceaccount.com \
          --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
